### PR TITLE
Pymaze challenge

### PR DESCRIPTION
**Pull request by sujith-rek**
## Summary
This PR is to add a challenge according to my GSOC proposal,
Students need to code a way out of the maze tackle zombies

Todo:
- [x] Unittest to grade 
- [x] Code clean up and setting up of goals
- [x] function which will check of the code successfully worked or not
- [x] preferred logic

## Checklist

- [x] Variables, functions and comments are translated to Spanish
- [x] Functions follow underscore notation
- [x] Spell check done & typos fixed
- [x] All python code is PEP8 compliant
- [x] Test coverage with Playwright implemented; locators are Pyhton code
- [x] Reviewers assigned (all peers & at least 1 mentor)

## Screenshots
image

when zombie is hit
image

### CODE REVIEW

**Comment by sujith-rek** [comment]
@reingart @NicolasSandoval 
I wrote a sample code under the function `solveMaze`
which will take the maze object and tries to solve the maze programmatically 

if a solution exists to the maze, it'll return true 
else returns false


This is the function that we will give to students to write their code for solving the maze
In unittest for grading, we will call this function and see if its working or not

**Comment by sujith-rek** [comment]
Brython is not supporting `unittest.TestCaseGui`
so i'm exploring some other ways to get done with unittests

**Comment by sujith-rek** [comment]
@NicolasSandoval as babynames challenge merged, I'm changing these file names and exercises to reto04?

**Comment by NicolasSandoval** [comment]
> @NicolasSandoval as babynames challenge merged, I'm changing these file names and exercises to reto04?

Hi @sujith-rek!, this challenge needs to be renamed to `Reto05` now.

**Comment by NicolasSandoval** [comment]
You could use a pythonic way in the class methods names, like `snake_case`.

**Comment by NicolasSandoval** [comment]
You could also add in the description of `solve_maze` that the function returns a boolean, eg "returns True if it has a solution or False instead" for clarity.

**Review by NicolasSandoval — APPROVED** [review]
Good job on the pymaze @sujith-rek! Thanks for adding a new pygame challenge.

**Pull request merged**
