### PR TITLE
Variables y entrada de datos (TWP05) fix typo

### PR DESCRIPTION
**Pull request by LeoCumpli21**
## Summary

This PR closes LeoCumpli21/PyZombis#30. I fixed a typo that prevented a CodeLens snippet from running. I also changed all `ActiveCode` and `CodeLens` IDs to be ac_l05_# or cl_l05_# respectively.
**Note**: I didn't focus on changing the redaction of the text, nor any grammar mistakes. 

## Checklist

- [x] Variables, functions and comments are translated to Spanish
- [x] Functions follow underscore notation
- [x] Spell check done & typos fixed
- [x] All python code is PEP8 compliant
- [x] Test coverage with Playwright implemented; locators are Pyhton code
- [x] Reviewers assigned (all peers & at least 1 mentor)

### CODE REVIEW

**Comment by LeoCumpli21** [comment]
Is it necessary to create a web test for a CodeLens exercise?

**Review by angelasofiaremolinagutierrez — CHANGES_REQUESTED** [review]
As we agreed on the last meeting codelens should only test the run button, so add one test that pushes the button and display what is supposed to display.

**Review by angelasofiaremolinagutierrez — APPROVED** [review]
No test is needed, my mistake ;)

**Review by y-martinez — CHANGES_REQUESTED** [review]
@LeoCumpli21 I saw that some of the ``codelens``  code doesn't follow the PEP8 rules, run ``black`` in that portion of code as well for example in the https://github.com/PyAr/PyZombis/blob/21c908b9fd83abe047db95c4b550425b3e59e8e0/_sources/lectures/TWP05.rst#L170-L177

According ``black`` they should be 

```python
print(2 + 3)
print(5 - 3)
print(10 - 4 + 2)
print(2 * 10)
print(10 / 4)
print(2 ** 3)
print(10 % 3)
print(16 % 7)
```

Check this in all codelens 👍🏼 but in genera it is good

**Review by y-martinez — APPROVED** [review]
LGTM!

**Review by NicolasSandoval — APPROVED** [review]
Great work!!

**Pull request merged**
