### PR TITLE
Split TWP05: Variables y entrada de datos

### PR DESCRIPTION
**Pull request by angelasofiaremolinagutierrez**
## Summary

This PR resolves https://github.com/angelasofiaremolinagutierrez/PyZombis/issues/24
Lecture `TWP05: Variables y entrada de datos` is now splitted into 16 sub-lectures. Check it out!

## Checklist

- [x] Variables, functions and comments are translated to Spanish
- [x] Functions follow underscore notation
- [x] Spell check done & typos fixed
- [x] All python code is PEP8 compliant
- [x] Test coverage with Playwright implemented; locators are Pyhton code
- [x] Reviewers assigned (all peers & at least 1 mentor)

## Screenshots

Sub-toctree of the lecture `TWP05: Variables y entrada de datos`
image

### CODE REVIEW

**Review by LeoCumpli21 — CHANGES_REQUESTED** [review]
Looks great! I have only one suggestion. Apply the same criterion that you established in #132 to the ids of the activecode and codelens snippets.

**Review by LeoCumpli21 — APPROVED** [review]
LGTM! 🚀

**Review by y-martinez — APPROVED** [review]
LGTM

**Review by NicolasSandoval — APPROVED** [review]
LGTM!

**Pull request merged**
