### PR TITLE
Added lectures into Runestone layout & few code samples.

### PR DESCRIPTION
**Pull request by urstrulykkr**
PULL REQUEST on issue #6. 

I've edited the index.rst file with two code samples. I dragged the lectures into the (pyzombis ) Runestone layout. Understood the setup.
Waiting to get my task reviewed by @reingart .

### CODE REVIEW

**Comment by reingart** [comment]
Thanks for the contribution!

A quick review:
 * I only see the sample project created by `runestone init` (only the title says "Python para Zombis")
 * Lectures were moved but not added to the index, so they do not appear online at all.
 * The 2nd code snippet has a syntax error
 * The multiple choice is just a sample

The ticket #6 is about moving the whole course structure to runestone, so all lectures should be linked in the index.
It would be great if you can migrate code snippets and create a quiz (multiple choice) for the first chapters.
TWP05.rst is the minimum, but as much you can migrate, it would be better to see if there are any hidden difficulty.

**Comment by urstrulykkr** [comment]
Thanks for the review @reingart .  Would surely get back to this soon :)

**Comment by urstrulykkr** [comment]
@reingart  as you said to link the lectures into the index.rst, should I use Hyperlinks (in reStructuredText)?
Links to all lectures in the index.rst itself.

**Comment by urstrulykkr** [comment]
I'm getting this 
` WARNING: toctree contains reference to nonexisting document u'PyZombis/pyzombislectures/TWP05'
`
I'm referencing with respect to my local environment.
I'm going through the Spinx docs, your help would be appreciated.

**Comment by urstrulykkr** [comment]
Screenshot from 2019-03-15 21-57-45
Screenshot from 2019-03-15 22-00-59


I'm had linked the lecture files into the index.rst.
But it says ....

`WARNING: undefined label: lectures/twp05.rst (if the link has no caption the label must precede a section header)
`

I had also refered the Sphninx docs. Need help.

**Comment by urstrulykkr** [comment]
Here it also precedes a section header.
Is my referencing wrong or any other issue?

**Comment by urstrulykkr** [comment]
@reingart  I have added all the lectures to the index.rst and also added few code snippets and quizzes for chapter 1. Hope to hear your review for the same.

**Pull request closed without merging**
